### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by rockrabbit** [mikebrady/alac#1]
I get the following error when install your ALAC

`aclocal: warning: couldn't open directory 'm4': No such file or directory`

Both on my Raspberry Pi3 and my Pi Zero

**Comment by mikebrady** [comment]
Thanks for the report. Did you try `$ autoreconf -fi`?

**Comment by rockrabbit** [comment]
Yes, thats where the error comes in

**Comment by mikebrady** [comment]
Okay, thanks. I'll have to try it on a clean installation. It'll be a day or so...

**Comment by mikebrady** [comment]
So, I had a look at this on a clean Raspberry Pi (original model). I got:
```
pi@raspberrypi:~/alac $ autoreconf -fi
aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:40: installing './compile'
configure.ac:63: installing './config.guess'
configure.ac:63: installing './config.sub'
configure.ac:20: installing './install-sh'
configure.ac:20: installing './missing'
Makefile.am: installing './INSTALL'
codec/Makefile.am: installing './depcomp'
pi@raspberrypi:~/alac $ 
```
So, there was a warning alright, but everything went fine. It did take quite a long time, but eventually finished successfully.

**Comment by rockrabbit** [comment]
Yip, the same thing on my end.. and yes it did install... checked and there was a m4 folder with content in it!

How do a confirm that Shairport Sync is actually using it?

**Comment by mikebrady** [comment]
You need to select it in the config file, and then if you have `log_verbosity` set at 2 (maybe at 1 as well – I can't remember just now) it will tell you which decoder it's using.

**Comment by rockrabbit** [comment]
I have set it in the config file....

under General:

`alac_decoder = "apple";`

Where will I find the log?

**Comment by mikebrady** [comment]
So, in the config file at `/etc/shairport-sync.conf` – there is a new setting for telling it which decoder to use (maybe you should look into the sample file at `/etc/shairport-sync.conf.sample` to see what I mean). Also, you can set the verbosity of the logging that Shairport Sync does. Normally it's 0, so only informational stuff is output, but you can set it to 1, 2 or 3 to get a little, a lot, or loads of log output in the system log.

**Comment by rockrabbit** [comment]
`Mar  4 19:18:27 pizero shairport-sync[603]: Apple ALAC Decoder used on encrypted audio.`

And happiness was his name! 👍

**Comment by mikebrady** [comment]
Splendid. Enjoy!
