### ISSUE TITLE
Makefile.am: error: required file './README' not found

### ISSUE THREAD

**Issue by Vaskyy** [mikebrady/alac#13]
Hello there,
i installed shairport-sync and it works flawlessly.

I assume i get better results here when configuring with ALAC? like more kHz?
![IMG_3857small](https://github.com/user-attachments/assets/a7ab9a33-16b0-44c0-b17d-e3f84e7f7bf0)

Now i wanted to make ALAC working, but i cant proceed in ur tutorial.
After i use the "autoreconf -fi" command i get this:

```
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:40: installing './compile'
configure.ac:20: installing './missing'
Makefile.am: error: required file './README' not found
codec/Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
```

And "make" doesnt work afterwards:
`make: *** No targets specified and no makefile found.  Stop.`

Did i do something wrong?

Hardware: **Raspberry Pi 2 Model B Rev 1.1**
Operating System: **Raspbian GNU/Linux 11 (bullseye)**
Kernel: **Linux 6.1.21-v7+**

**Comment by mikebrady** [comment]
Thanks for this.

Two parts to the answer:
1. The ALAC library will not result in better decoding -- the built-in decoder is just as good. Unfortunately, both have bugs when dealing with invalid inputs.
2. Thanks for the bug report -- fixed now.

**Comment by Vaskyy** [comment]
Damn thanks for the quick response :)
So it doesn't bring any benefits using the alac library?
May I ask what's it being used for then?

**Comment by mikebrady** [comment]
It was really done as an experiment, so see if it would make any difference, but as far as we can see and hear, it didn’t. 😕
