### ISSUE TITLE
Test ALAC decoding

### ISSUE THREAD

**Issue by meduser** [mikebrady/alac#3]
How can I test if shairport is using ALAC to decode the audio after installation and setting it up in config?

**Comment by mikebrady** [comment]
Thanks for the post. Once you have compiled it into Shairport Sync and enabled it in the config file, the log will indicate that it’s been selected. To prove this, one way would be to put in a debug message in part of the code that is only ever executed when the ALAC decoder is being used. Is that the kind of thing you mean?
