### ISSUE TITLE
configure fails with error: cannot find input file: `codec/Makefile.in'

### ISSUE THREAD

**Issue by funkeeflow** [mikebrady/alac#5]
Tried this on Raspberry Pi Model 3B with STRETCH LITE 2018-06-27.

Output:
...
./configure: line 5027: LT_INIT: command not found
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: error: cannot find input file: `codec/Makefile.in'

Any suggestions would be appreciated :)

cheers

**Comment by mikebrady** [comment]
Thanks for the post. I’ll check it later today — in a few hours.

**Comment by funkeeflow** [comment]
apt-get install autoconf automake libtool libdaemon-dev libpopt-dev libconfig-dev

and running
libtoolize
aclocal
autoconf
autoheader
automake --add-missing

fixed the issue.

**Comment by mikebrady** [comment]
Thanks. Probably as bit of overkill in all that, but good that it worked for you.

**Comment by mikebrady** [comment]
I updated the [README.md](https://github.com/mikebrady/alac/blob/master/README.md) to specify the tools needed. Thanks again for your help.
